import { useCallback, useEffect, useState } from "react";
import { ApiError, apiRequest } from "@/lib/api/client";

export interface SiemAlertSource { name: string; ip?: string | null; agent_id?: string | null; agent_name?: string | null; }
export interface SiemMitre { id: string[]; tactic: string[]; technique: string[]; }
export interface SiemAlert { id: string; timestamp: string; title: string; description?: string | null; severity: number; source: SiemAlertSource; rule_id: string; mitre?: SiemMitre | null; raw_data: Record<string, unknown>; tags: string[]; }
export interface SiemAgent { id: string; name: string; ip?: string | null; os_name?: string | null; os_version?: string | null; status: string; last_keepalive?: string | null; version?: string | null; }
export interface AlertListResponse { total: number; items: SiemAlert[]; }
export interface AgentListResponse { total: number; items: SiemAgent[]; }
type ResourceState<T> = { status: "loading"; data: T[]; error: null } | { status: "ready" | "empty"; data: T[]; error: null } | { status: "unauthorized" | "unavailable" | "error"; data: T[]; error: ApiError };
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function string(value: unknown): value is string { return typeof value === "string"; }
function strings(value: unknown): value is string[] { return Array.isArray(value) && value.every(string); }
function timestamp(value: unknown): value is string { return string(value) && !Number.isNaN(Date.parse(value)); }
function nullableString(value: unknown): value is string | null | undefined { return value === undefined || value === null || string(value); }
function parseSource(value: unknown): SiemAlertSource | null { if (!record(value) || !string(value.name) || !nullableString(value.ip) || !nullableString(value.agent_id) || !nullableString(value.agent_name)) return null; return { name: value.name, ...(value.ip !== undefined ? { ip: value.ip as string | null } : {}), ...(value.agent_id !== undefined ? { agent_id: value.agent_id as string | null } : {}), ...(value.agent_name !== undefined ? { agent_name: value.agent_name as string | null } : {}) }; }
function parseMitre(value: unknown): SiemMitre | null { if (!record(value) || !strings(value.id) || !strings(value.tactic) || !strings(value.technique)) return null; return { id: value.id, tactic: value.tactic, technique: value.technique }; }
function parseAlert(value: unknown): SiemAlert | null { if (!record(value) || !string(value.id) || !timestamp(value.timestamp) || !string(value.title) || !nullableString(value.description) || typeof value.severity !== "number" || value.severity < 0 || value.severity > 15 || !string(value.rule_id) || !strings(value.tags) || !record(value.raw_data)) return null; const source = parseSource(value.source); const mitre = value.mitre === null || value.mitre === undefined ? value.mitre : parseMitre(value.mitre); if (!source || (value.mitre !== null && value.mitre !== undefined && !mitre)) return null; return { id: value.id, timestamp: value.timestamp, title: value.title, severity: value.severity, source, rule_id: value.rule_id, raw_data: value.raw_data, tags: value.tags, ...(value.description !== undefined ? { description: value.description as string | null } : {}), ...(mitre !== undefined ? { mitre } : {}) }; }
function parseAgent(value: unknown): SiemAgent | null { if (!record(value) || !string(value.id) || !string(value.name) || !string(value.status) || !nullableString(value.ip) || !nullableString(value.os_name) || !nullableString(value.os_version) || !nullableString(value.version) || (value.last_keepalive !== undefined && value.last_keepalive !== null && !timestamp(value.last_keepalive))) return null; return { id: value.id, name: value.name, status: value.status, ...(value.ip !== undefined ? { ip: value.ip as string | null } : {}), ...(value.os_name !== undefined ? { os_name: value.os_name as string | null } : {}), ...(value.os_version !== undefined ? { os_version: value.os_version as string | null } : {}), ...(value.version !== undefined ? { version: value.version as string | null } : {}), ...(value.last_keepalive !== undefined ? { last_keepalive: value.last_keepalive as string | null } : {}) }; }
function parseEnvelope<T>(value: unknown, parse: (item: unknown) => T | null): { total: number; items: T[] } { if (!record(value) || typeof value.total !== "number" || !Array.isArray(value.items)) throw new ApiError("The SIEM service returned an unexpected response.", 500); const items = value.items.map(parse); if (items.some((item) => item === null)) throw new ApiError("The SIEM service returned an unexpected response.", 500); return { total: value.total, items: items as T[] }; }
async function request<T>(path: string, parse: (value: unknown) => T): Promise<T> { try { return parse(await apiRequest<unknown>(path)); } catch (cause) { if (cause instanceof ApiError || (cause instanceof Error && cause.name === "AbortError")) throw cause; throw new ApiError("The Wazuh integration is unavailable.", 503); } }
export function getAlerts(limit = 50): Promise<AlertListResponse> { const params = new URLSearchParams({ limit: String(limit) }); return request(`siem/alerts?${params.toString()}`, (value) => parseEnvelope(value, parseAlert)); }
export function getAgents(): Promise<AgentListResponse> { return request("siem/agents", (value) => parseEnvelope(value, parseAgent)); }
function useResource<T>(loader: () => Promise<{ items: T[] }>) { const [state, setState] = useState<ResourceState<T>>({ status: "loading", data: [], error: null }); const load = useCallback(async () => { setState((current) => ({ ...current, status: "loading", error: null })); try { const result = await loader(); setState({ status: result.items.length ? "ready" : "empty", data: result.items, error: null }); } catch (cause) { const error = cause instanceof ApiError ? cause : new ApiError("SIEM data could not be loaded.", 500); const status = error.status === 401 ? "unauthorized" : error.status === 502 || error.status === 503 || error.status === 504 ? "unavailable" : "error"; setState({ status, data: [], error }); } }, [loader]); useEffect(() => { void Promise.resolve().then(load); }, [load]); return { ...state, refresh: load }; }
export function useSiemAlerts() { return useResource<SiemAlert>(useCallback(() => getAlerts(), [])); }
export function useSiemAgents() { return useResource<SiemAgent>(useCallback(() => getAgents(), [])); }
