import { ApiError, apiRequest } from "@/lib/api/client";

export const IOC_TYPES = ["ip", "domain", "url", "hash", "cve"] as const;
export type IocType = typeof IOC_TYPES[number];
export const RISK_LEVELS = ["clean", "low", "medium", "high", "critical", "unknown"] as const;
export type RiskLevel = typeof RISK_LEVELS[number];
export type ThreatProvider = { provider_name: string; is_malicious: boolean; confidence: number; tags: string[] };
export type ThreatIntelResult = { ioc_value: string; ioc_type: IocType; risk_level: RiskLevel; risk_score: number; tags: string[]; related_cves: string[]; related_malware: string[]; providers: ThreatProvider[]; country?: string | null; asn?: string | null; file_type?: string | null; cvss_score?: number | null; cwe?: string | null };
const record = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const string = (value: unknown): value is string => typeof value === "string";
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every(string);
const nullableString = (value: unknown) => value === undefined || value === null || string(value);
const type = (value: unknown): value is IocType => string(value) && IOC_TYPES.includes(value as IocType);
const risk = (value: unknown): value is RiskLevel => string(value) && RISK_LEVELS.includes(value as RiskLevel);
function parseProvider(value: unknown): ThreatProvider | null { if (!record(value) || !string(value.provider_name) || typeof value.is_malicious !== "boolean" || typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 100 || !strings(value.tags)) return null; return { provider_name: value.provider_name, is_malicious: value.is_malicious, confidence: value.confidence, tags: value.tags }; }
function parseResult(value: unknown): ThreatIntelResult { if (!record(value) || !string(value.ioc_value) || !type(value.ioc_type) || !risk(value.risk_level) || typeof value.risk_score !== "number" || value.risk_score < 0 || value.risk_score > 100 || !strings(value.tags) || !strings(value.related_cves) || !strings(value.related_malware) || !Array.isArray(value.providers) || !nullableString(value.country) || !nullableString(value.asn) || !nullableString(value.file_type) || !nullableString(value.cwe) || (value.cvss_score !== undefined && value.cvss_score !== null && typeof value.cvss_score !== "number")) throw new ApiError("The threat intelligence service returned an unexpected response.", 500); const providers = value.providers.map(parseProvider); if (providers.some((provider) => provider === null)) throw new ApiError("The threat intelligence service returned an unexpected response.", 500); return { ioc_value: value.ioc_value, ioc_type: value.ioc_type, risk_level: value.risk_level, risk_score: value.risk_score, tags: value.tags, related_cves: value.related_cves, related_malware: value.related_malware, providers: providers as ThreatProvider[], ...(value.country !== undefined ? { country: value.country as string | null } : {}), ...(value.asn !== undefined ? { asn: value.asn as string | null } : {}), ...(value.file_type !== undefined ? { file_type: value.file_type as string | null } : {}), ...(value.cvss_score !== undefined ? { cvss_score: value.cvss_score as number | null } : {}), ...(value.cwe !== undefined ? { cwe: value.cwe as string | null } : {}) }; }
export async function lookupIoc(iocValue: string, iocType: IocType): Promise<ThreatIntelResult> { const query = new URLSearchParams({ ioc_value: iocValue, ioc_type: iocType }); try { return parseResult(await apiRequest<unknown>(`threat-intel/lookup?${query.toString()}`)); } catch (cause) { if (cause instanceof ApiError) throw cause; throw new ApiError("Threat intelligence could not be loaded.", 503); } }
