"""Initial schema

Revision ID: 198f17676aa3
Revises: 
Create Date: 2026-07-21 23:42:59.747780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.database import VariantArray, VariantJSON

# revision identifiers, used by Alembic.
revision: str = '198f17676aa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('asset_type', sa.Enum('SERVER', 'WORKSTATION', 'VM', 'CONTAINER', 'WEB_APP', 'HONEYPOT', name='asset_type_enum'), nullable=False),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', name='environment_enum'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticality_enum'), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('tags', VariantArray(sa.String()), nullable=True),
    sa.Column('has_wazuh_agent', sa.Boolean(), nullable=True),
    sa.Column('protected_by_waf', sa.Boolean(), nullable=True),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CONTAINED', 'RESOLVED', 'CLOSED', name='incident_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_analyst', sa.String(), nullable=True),
    sa.Column('related_assets', VariantArray(sa.String()), nullable=True),
    sa.Column('related_mitre_tactics', VariantArray(sa.String()), nullable=True),
    sa.Column('playbook_id', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tactics', VariantArray(sa.String()), nullable=True),
    sa.Column('data_sources', VariantArray(sa.String()), nullable=True),
    sa.Column('mitigations', VariantArray(sa.String()), nullable=True),
    sa.Column('coverage', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='coverage_level_enum'), nullable=True),
    sa.Column('linked_sigma_rules', VariantArray(sa.String()), nullable=True),
    sa.Column('linked_wazuh_rules', VariantArray(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_id'), 'mitre_techniques', ['id'], unique=False)
    op.create_table('sigma_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logsource', VariantJSON(), nullable=True),
    sa.Column('detection_logic', VariantJSON(), nullable=True),
    sa.Column('falsepositives', VariantArray(sa.String()), nullable=True),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='rule_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TESTING', 'DEPRECATED', name='rule_status_enum'), nullable=True),
    sa.Column('tags', VariantArray(sa.String()), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('raw_yaml', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigma_rules_id'), 'sigma_rules', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permissions', VariantArray(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_id'), 'incident_evidence', ['id'], unique=False)
    op.create_table('incident_timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('raw_data', VariantJSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_events_id'), 'incident_timeline_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_timeline_events_id'), table_name='incident_timeline_events')
    op.drop_table('incident_timeline_events')
    op.drop_index(op.f('ix_incident_evidence_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sigma_rules_id'), table_name='sigma_rules')
    op.drop_table('sigma_rules')
    op.drop_index(op.f('ix_mitre_techniques_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
