"use client";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState, ErrorState, IntegrationUnavailableState, LoadingState, UnauthorizedState } from "@/components/system/feedback";
import { PageContainer, PageHeader } from "@/components/system/page";
import { ApiError } from "@/lib/api/client";
import { type DetectionRule, getDetectionRules } from "@/lib/api/detection";
export default function DetectionPage() { const [rules, setRules] = useState<DetectionRule[] | null>(null); const [error, setError] = useState<ApiError | null>(null); const [loading, setLoading] = useState(true); const load = async () => { setLoading(true); setError(null); try { setRules(await getDetectionRules()); } catch (cause) { setError(cause instanceof ApiError ? cause : new ApiError("Detection rules could not be loaded.", 500)); } finally { setLoading(false); } }; useEffect(() => { void Promise.resolve().then(load); }, []); if (loading && rules === null) return <PageContainer><LoadingState label="Loading detection rules…" /></PageContainer>; if (error?.status === 401) return <PageContainer><UnauthorizedState /></PageContainer>; if (error) return <PageContainer>{error.status >= 502 ? <IntegrationUnavailableState integrationName="Detection service" reason="The service did not respond." guidance="Try again later." action={<Button onClick={() => void load()}>Retry</Button>} /> : <ErrorState title="Detection rules unavailable" description="Rules could not be loaded." onRetry={() => void load()} />}</PageContainer>; return <PageContainer><PageHeader title="Detection Engineering" description="Loaded detection rules from the configured rule library." actions={<Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "animate-spin" : ""} />Refresh</Button>} />{!rules?.length ? <EmptyState title="No detection rules" description="The configured rule library returned no records." /> : <div className="panel overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><caption className="sr-only">Loaded detection rules</caption><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="p-3">Rule</th><th className="p-3">Severity</th><th className="p-3">Status</th><th className="p-3">MITRE tags</th><th className="p-3">Updated</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id} className="border-b"><td className="p-3"><p className="font-medium">{rule.title}</p><p className="font-mono text-xs text-muted-foreground">{rule.id}</p></td><td className="p-3">{rule.level}</td><td className="p-3">{rule.status}</td><td className="p-3">{rule.tags.filter((tag) => tag.startsWith("attack.")).join(", ") || "Not provided"}</td><td className="p-3">{new Date(rule.date).toLocaleString()}</td></tr>)}</tbody></table></div>}</PageContainer>; }
