"use client";

import { FormEvent, useState } from "react";
import { Search } from "lucide-react";
import { ErrorState, IntegrationUnavailableState, UnauthorizedState } from "@/components/system/feedback";
import { PageContainer, PageHeader } from "@/components/system/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ApiError } from "@/lib/api/client";
import { IOC_TYPES, type IocType, type ThreatIntelResult, lookupIoc } from "@/lib/api/threat-intel";

export default function ThreatIntelPage() {
  const [iocValue, setIocValue] = useState(""); const [iocType, setIocType] = useState<IocType>("ip"); const [result, setResult] = useState<ThreatIntelResult | null>(null); const [error, setError] = useState<ApiError | null>(null); const [validationError, setValidationError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const value = iocValue.trim(); if (submitting) return; if (!isValidIoc(value, iocType)) { setValidationError(`Enter a valid ${iocType.toUpperCase()} indicator.`); return; } setSubmitting(true); setError(null); setValidationError(null); setResult(null); try { setResult(await lookupIoc(value, iocType)); } catch (cause) { setError(cause instanceof ApiError ? cause : new ApiError("Threat intelligence could not be loaded.", 500)); } finally { setSubmitting(false); } };
  return <PageContainer>
    <PageHeader title="Threat Intelligence" description="Look up a submitted indicator only through configured intelligence providers." />
    <section className="panel p-5"><h2 className="text-base font-semibold">IOC lookup</h2><p className="mt-1 text-sm text-muted-foreground">Results are provider-reported facts where available; they are not a verdict or an automated response.</p><form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={submit}><div className="min-w-0 flex-1"><label className="sr-only" htmlFor="ioc-value">Indicator value</label><Input id="ioc-value" value={iocValue} onChange={(event) => setIocValue(event.target.value)} placeholder="Enter an indicator" disabled={submitting} aria-describedby={validationError ? "ioc-error" : undefined} required /></div><label className="sr-only" htmlFor="ioc-type">Indicator type</label><select id="ioc-type" className="h-10 rounded-md border bg-background px-3 text-sm" value={iocType} onChange={(event) => setIocType(event.target.value as IocType)} disabled={submitting}>{IOC_TYPES.map((type) => <option key={type} value={type}>{type.toUpperCase()}</option>)}</select><Button type="submit" disabled={submitting}><Search aria-hidden="true" />{submitting ? "Looking up…" : "Lookup IOC"}</Button></form>{validationError && <p id="ioc-error" className="mt-3 text-sm text-destructive" role="alert">{validationError}</p>}</section>
    {error?.status === 401 && <UnauthorizedState title="Access unavailable" description="You are not authorized to query threat intelligence." />}
    {error && error.status !== 401 && (error.status === 502 || error.status === 503 || error.status === 504 ? <IntegrationUnavailableState integrationName="Threat intelligence" reason="No configured provider responded." guidance="Your submitted indicator was not classified." /> : <ErrorState title="Lookup failed" description="Threat intelligence could not be loaded. Try again." />)}
    {result && <ResultCard result={result} />}
  </PageContainer>;
}
function ResultCard({ result }: { result: ThreatIntelResult }) { return <section className="panel p-5"><h2 className="font-semibold">Lookup result</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Detail label="Indicator" value={result.ioc_value} /><Detail label="Type" value={result.ioc_type.toUpperCase()} /><Detail label="Provider classification" value={result.risk_level} /><Detail label="Provider score" value={`${result.risk_score} / 100`} /><Detail label="Tags" value={result.tags.length ? result.tags.join(", ") : "Not provided"} /><Detail label="Providers" value={result.providers.length ? result.providers.map((provider) => provider.provider_name).join(", ") : "No intelligence found"} /></dl><p className="mt-5 text-sm text-muted-foreground">Verify provider-reported information before making an analyst decision.</p></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value}</dd></div>; }
function isValidIoc(value: string, type: IocType) { if (!value) return false; if (type === "ip") return /^((25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(25[0-5]|2[0-4]\d|1?\d?\d)$/.test(value) || value.includes(":"); if (type === "domain") return /^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(value); if (type === "url") { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:"; } catch { return false; } } if (type === "hash") return /^[a-f0-9]{32}$|^[a-f0-9]{40}$|^[a-f0-9]{64}$|^[a-f0-9]{128}$/i.test(value); return /^CVE-\d{4}-\d{4,}$/i.test(value); }
