"use client";
import { FormEvent, useState } from "react";
import { FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ErrorState, IntegrationUnavailableState, UnauthorizedState } from "@/components/system/feedback";
import { PageContainer, PageHeader } from "@/components/system/page";
import { ApiError } from "@/lib/api/client";
import { type ReportFormat, type ReportResponse, generateReport } from "@/lib/api/reports";
export default function ReportsPage() { const [incidentId, setIncidentId] = useState(""); const [format, setFormat] = useState<ReportFormat>("pdf"); const [result, setResult] = useState<ReportResponse | null>(null); const [error, setError] = useState<ApiError | null>(null); const [pending, setPending] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!incidentId.trim() || pending) return; setPending(true); setError(null); setResult(null); try { setResult(await generateReport(incidentId.trim(), format)); } catch (cause) { setError(cause instanceof ApiError ? cause : new ApiError("Report generation could not be completed.", 500)); } finally { setPending(false); } }; return <PageContainer><PageHeader title="Reports" description="Generate a report from a real incident record. No report history or scheduled delivery is configured." /><section className="panel p-5"><h2 className="font-semibold">Generate incident report</h2><form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={submit}><div className="flex-1"><label className="sr-only" htmlFor="report-incident">Incident ID</label><Input id="report-incident" value={incidentId} onChange={(event) => setIncidentId(event.target.value)} placeholder="Incident ID" required disabled={pending} /></div><select className="h-10 rounded-md border bg-background px-3" value={format} onChange={(event) => setFormat(event.target.value as ReportFormat)} disabled={pending} aria-label="Report format"><option value="pdf">PDF</option><option value="html">HTML</option></select><Button type="submit" disabled={pending}><FileText aria-hidden="true" />{pending ? "Generating…" : "Generate"}</Button></form></section>{error?.status === 401 && <UnauthorizedState />}{error && error.status !== 401 && (error.status >= 502 ? <IntegrationUnavailableState integrationName="Reports" reason="The report service did not respond." guidance="Try again later." /> : <ErrorState title="Report unavailable" description="The report could not be generated." />)}{result && <section className="panel p-5"><h2 className="font-semibold">Report generated</h2><p className="mt-1 text-sm text-muted-foreground">The server generated a {result.format.toUpperCase()} report for {result.incident_id}.</p><Button className="mt-4" render={<a href={`/api/${result.download_url.replace(/^\/api\/v1\//, "")}`}>Download report</a>} /></section>}</PageContainer>; }
