const now = "2026-10-03T15:30:00Z";

export const demoUser = {
  id: "demo-analyst",
  email: "demo.analyst@mithilkg.dev",
  full_name: "Recruiter SOC Demo",
  role: "SOC Analyst",
  permissions: [
    "incidents:read",
    "assets:read",
    "siem:read",
    "rules:read",
    "threat_intel:read",
    "mitre:read",
    "reports:read",
    "audit:read",
  ],
  is_active: true,
};

export const demoIncidents = [
  {
    id: "INC-001",
    title: "Authentication anomaly",
    description: "Repeated failed sign-in activity followed by analyst triage.",
    severity: "High",
    status: "Open",
    created_at: "2026-10-03T12:10:00Z",
    updated_at: "2026-10-03T15:20:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-001"],
    related_mitre_tactics: ["Credential Access"],
    timeline: [
      { id: "EV-001", timestamp: "2026-10-03T12:10:00Z", source: "Windows Security", description: "Multiple failed logons observed." },
      { id: "EV-002", timestamp: "2026-10-03T12:16:00Z", source: "Wazuh", description: "Correlation rule raised an analyst alert." },
    ],
    evidence: [],
    ai_summary: null,
  },
  {
    id: "INC-002",
    title: "PowerShell activity",
    description: "PowerShell telemetry reviewed against a controlled lab scenario.",
    severity: "Medium",
    status: "In Progress",
    created_at: "2026-10-03T12:40:00Z",
    updated_at: "2026-10-03T15:05:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-001"],
    related_mitre_tactics: ["Execution"],
    timeline: [],
    evidence: [],
    ai_summary: null,
  },
  {
    id: "INC-003",
    title: "Scheduled task activity",
    description: "Controlled persistence activity captured and reviewed.",
    severity: "Medium",
    status: "Contained",
    created_at: "2026-10-03T13:05:00Z",
    updated_at: "2026-10-03T14:55:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-001"],
    related_mitre_tactics: ["Persistence"],
    timeline: [],
    evidence: [],
    ai_summary: null,
  },
  {
    id: "INC-004",
    title: "Sensitive process discovery",
    description: "Safe discovery test produced partial telemetry.",
    severity: "High",
    status: "Open",
    created_at: "2026-10-03T13:30:00Z",
    updated_at: "2026-10-03T14:40:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-001"],
    related_mitre_tactics: ["Discovery"],
    timeline: [],
    evidence: [],
    ai_summary: null,
  },
  {
    id: "INC-005",
    title: "Web application security event",
    description: "Synthetic application event reviewed through the incident workflow.",
    severity: "High",
    status: "Resolved",
    created_at: "2026-10-03T11:20:00Z",
    updated_at: "2026-10-03T14:20:00Z",
    closed_at: "2026-10-03T14:20:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-002"],
    related_mitre_tactics: ["Initial Access"],
    timeline: [],
    evidence: [],
    ai_summary: null,
  },
  {
    id: "INC-006",
    title: "Data transfer event",
    description: "Controlled transfer event preserved with integrity evidence.",
    severity: "Medium",
    status: "Resolved",
    created_at: "2026-10-03T10:15:00Z",
    updated_at: "2026-10-03T13:50:00Z",
    closed_at: "2026-10-03T13:50:00Z",
    assigned_analyst: "Recruiter SOC Demo",
    related_assets: ["AST-001", "AST-002"],
    related_mitre_tactics: ["Exfiltration"],
    timeline: [],
    evidence: [],
    ai_summary: null,
  },
];

export const demoAssets = [
  {
    id: "AST-001",
    hostname: "win-endpoint-01",
    ip_address: "10.10.20.15",
    os_name: "Windows 11",
    asset_type: "Workstation",
    environment: "Development",
    criticality: "High",
    owner: "Cyber Defense Lab",
    tags: ["lab", "endpoint"],
    has_wazuh_agent: true,
    protected_by_waf: false,
    is_internet_facing: false,
    last_seen: now,
    health_status: "Healthy",
  },
  {
    id: "AST-002",
    hostname: "web-lab-01",
    ip_address: "10.10.30.20",
    os_name: "Ubuntu",
    asset_type: "Web App",
    environment: "Development",
    criticality: "Medium",
    owner: "Cyber Defense Lab",
    tags: ["lab", "web"],
    has_wazuh_agent: true,
    protected_by_waf: true,
    is_internet_facing: false,
    last_seen: now,
    health_status: "Healthy",
  },
  {
    id: "AST-003",
    hostname: "wazuh-manager",
    ip_address: "10.10.10.5",
    os_name: "Linux",
    asset_type: "Server",
    environment: "Development",
    criticality: "Critical",
    owner: "Cyber Defense Lab",
    tags: ["siem", "wazuh"],
    has_wazuh_agent: true,
    protected_by_waf: false,
    is_internet_facing: false,
    last_seen: now,
    health_status: "Healthy",
  },
];

export const demoAlerts = [
  {
    id: "ALT-001",
    timestamp: "2026-10-03T15:18:00Z",
    title: "Repeated authentication failures",
    description: "Synthetic authentication event correlation.",
    severity: 9,
    source: { name: "Wazuh", ip: "10.10.20.15", agent_id: "001", agent_name: "win-endpoint-01" },
    rule_id: "100201",
    mitre: { id: ["T1078"], tactic: ["Credential Access"], technique: ["Valid Accounts"] },
    raw_data: { demo: true },
    tags: ["authentication", "lab"],
  },
  {
    id: "ALT-002",
    timestamp: "2026-10-03T15:02:00Z",
    title: "PowerShell script block activity",
    description: "Controlled PowerShell telemetry.",
    severity: 7,
    source: { name: "Wazuh", ip: "10.10.20.15", agent_id: "001", agent_name: "win-endpoint-01" },
    rule_id: "92057",
    mitre: { id: ["T1059.001"], tactic: ["Execution"], technique: ["PowerShell"] },
    raw_data: { demo: true },
    tags: ["powershell", "lab"],
  },
  {
    id: "ALT-003",
    timestamp: "2026-10-03T14:35:00Z",
    title: "Scheduled task created",
    description: "Controlled scheduled task activity.",
    severity: 6,
    source: { name: "Wazuh", ip: "10.10.20.15", agent_id: "001", agent_name: "win-endpoint-01" },
    rule_id: "60228",
    mitre: { id: ["T1053"], tactic: ["Persistence"], technique: ["Scheduled Task/Job"] },
    raw_data: { demo: true },
    tags: ["persistence", "lab"],
  },
];

export const demoAgents = [
  { id: "001", name: "win-endpoint-01", ip: "10.10.20.15", os_name: "Windows", os_version: "11", status: "active", last_keepalive: now, version: "4.x" },
  { id: "002", name: "web-lab-01", ip: "10.10.30.20", os_name: "Linux", os_version: "Ubuntu", status: "active", last_keepalive: now, version: "4.x" },
];

export const demoRules = [
  { id: "SIG-001", title: "Repeated Failed Logons", description: "Detects repeated authentication failures.", logsource: { product: "windows", service: "security" }, level: "High", status: "Active", tags: ["attack.credential_access"], author: "Mithil K Gowda", date: "2026-10-01T00:00:00Z", raw_yaml: "title: Repeated Failed Logons" },
  { id: "SIG-002", title: "PowerShell Script Activity", description: "Detects controlled PowerShell script activity.", logsource: { product: "windows", service: "powershell" }, level: "Medium", status: "Active", tags: ["attack.execution"], author: "Mithil K Gowda", date: "2026-10-01T00:00:00Z", raw_yaml: "title: PowerShell Script Activity" },
  { id: "SIG-003", title: "Scheduled Task Creation", description: "Detects scheduled task creation in the lab.", logsource: { product: "windows", service: "security" }, level: "Medium", status: "Active", tags: ["attack.persistence"], author: "Mithil K Gowda", date: "2026-10-01T00:00:00Z", raw_yaml: "title: Scheduled Task Creation" },
];

export const demoMitre = [
  { id: "T1078", name: "Valid Accounts", description: "Account activity investigated in the authentication case.", tactics: ["Credential Access"], data_sources: ["Windows Security"], mitigations: ["Account monitoring"], coverage: "High", linked_sigma_rules: ["SIG-001"], linked_wazuh_rules: ["100201"] },
  { id: "T1059.001", name: "PowerShell", description: "PowerShell execution telemetry validated in the lab.", tactics: ["Execution"], data_sources: ["PowerShell"], mitigations: ["Script logging"], coverage: "High", linked_sigma_rules: ["SIG-002"], linked_wazuh_rules: ["92057"] },
  { id: "T1053", name: "Scheduled Task/Job", description: "Scheduled task activity validated in the lab.", tactics: ["Persistence"], data_sources: ["Windows Security"], mitigations: ["Monitor task creation"], coverage: "Medium", linked_sigma_rules: ["SIG-003"], linked_wazuh_rules: ["60228"] },
];

export const demoAudit = [
  { id: "AUD-001", user_email: "demo.analyst@mithilkg.dev", action: "view", target: "dashboard", resource_id: "overview", ip_address: "demo", user_agent: "recruiter-demo", result: "success", timestamp: now },
  { id: "AUD-002", user_email: "demo.analyst@mithilkg.dev", action: "view", target: "incident", resource_id: "INC-001", ip_address: "demo", user_agent: "recruiter-demo", result: "success", timestamp: "2026-10-03T15:22:00Z" },
];
